# Generated by Django 2.1.1 on 2018-09-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('created', models.DateTimeField(verbose_name='created date')),
                ('updated_date', models.DateTimeField(verbose_name='updated date')),
            ],
        ),
    ]
